export const BASE_URL = "http://localhost:8081";
export const API_BASE_URL = BASE_URL + "/api/v1";
export const PRODUCTS = "/products";
export const USER = "/users"
export const REGISTER = USER + "/register"
export const LOGIN = USER + "/login"
export const CART = "/cart"
export const ADD_TO_CART = CART + "/add-to-cart"
export const UPDATE_CART = CART + "/update"
export const CLEAR = "/clear"